wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1647848215
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.12
      5: 0.12.11
      8:
      - 3
      - 5
